### ISSUE TITLE
Enhance `ControlPlane` controller for Packet provider

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener-extensions#109]
We should implement `ControlPlane` extension resource controller for Packet similarly to how we did it for all other providers, e.g. [Alicloud](https://github.com/gardener/gardener-extensions/tree/master/controllers/provider-alicloud/pkg/controller/controlplane). Similarly to Alicloud, Packet has CSI plugin in addition to `cloud-controller-manager`. The relevant changes were recently merged as a botanist in Gardener.

Based on [the current implementation](https://github.com/gardener/gardener/blob/master/example/90-shoot-packet.yaml) the `ControlPlaneConfig` should look like this:

```yaml
apiVersion: packet.provider.extensions.gardener.cloud/v1alpha1
kind: ControlPlaneConfig
cloudControllerManager:
  featureGates:
    CustomResourceValidation: true
```

No `ControlPlaneStatus` needs to be implemented right now (not needed yet).
