### ISSUE TITLE
Errors in `cloud-controller-manager` logs

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener-extensions#112]
After starting, the `cloud-controller-manager` logs contain the following error:

```
E0609 08:41:31.554938       1 reflector.go:134] k8s.io/kubernetes/pkg/controller/cloud/pvlcontroller.go:115: Failed to list *v1.PersistentVolume: persistentvolumes is forbidden: User "system:serviceaccount:kube-system:pvl-controller" cannot list resource "persistentvolumes" in API group "" at the cluster scope
```

This is caused by the `pvl-controller` service account having insufficient RBAC privileges for persistent volumes. The following RBAC configuration should be added to Gardener (as a temporary fix) and to all controlplane controllers:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:pvl-controller
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:pvl-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:pvl-controller
subjects:
- kind: ServiceAccount
  name: pvl-controller
  namespace: kube-system
```
