### ISSUE TITLE
Control plane extension

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener-extensions#20]
# Overview

As of now, the creation of the control plane of a K8S cluster has been covered by some by parts of the `Generic` resource.

To proceed with full end-to-end extensibility, we must tackle this issue as well.

## Goals and assumptions

- provide building blocks for various K8S control plane implementations.
- Different cloud providers can implement add/remove (custom) control plane components.
  - one provider can run their muliple schedulers or run X amount of controllers in their cluster.
- Gardener should not know about about ordering/prerequisites for creation of said components - the flow is entirely handled by the specific cloud provider.
- Controllers provider by Gardener which handle the lifecycle of the most common componets in the control plane of a __standard__ Kubernetes cluster - `kube-apiserver`, `kube-controller-manager` and `kube-scheduler`.
- Gardener should create the K8S CRs mentioned bellow based on the Shoot specification.

## Ideas

This is **not** a complete or concrete specification, api-groups, resource names and so, just ideas on how different componets can look like and interact between eachother.

### kube-apiserver, kube-controller-manager and kube-scheduler

The Kubernetes API server has some edge cases where when upgrading you must be careful about:
- enabling feature gates as new fields can be introduced in the API leading to data loss
- migration of resources to different Groups / Versions
- service account credential rotation

```yaml
kind: KubeAPIServer
group: k8s.gardener.cloud/v1alpha1
metadata:
  name: foo
  namespace: baz
spec:
  config:
    anonymousAuth: false
    allowPrivileged: false
    # and so
  version: v1.13.5
status:
  version: v1.12.3
```

This will create/upgrade an existing `kube-apiserver` `Deployment` called `foo-kube-apiserver` in `baz` namespace.
Another benefit of having the `desired` configuration is the possibility of building compliance on top of it. (e.g. Don't allow API servers to have `spec.config.anonymousAuth: true`)

The same approach can be applied to `kube-controller-manager`, `kube-scheduler`:

```yaml
kind: KubeControllerManager
group: k8s.gardener.cloud/v1alpha1
metadata:
  name: foo
  namespace: baz
spec:
  # More or less
  # https://github.com/kubernetes/kube-controller-manager/blob/eae2e179736468e62ca019a10fea0a6551e24c9b/config/v1alpha1/types.go#L84
  config:
    kubeCloudSharedConfiguration:
      allocateNodeCIDRs: true
  version: v1.13.5
status:
  version: v1.12.3
```

```yaml
kind: KubeScheduler
group: k8s.gardener.cloud/v1alpha1
metadata:
  name: foo
  namespace: baz
spec:
  # More or less
  # https://github.com/kubernetes/kube-scheduler/blob/4ef011c65fa5c413f3989f5d4c28df7196d512b9/config/v1alpha1/types.go#L37
  config:
    schedulerName: default
  version: v1.13.5
status:
  version: v1.12.3
```

## Composition

After having those basic building blocks, we can build a composite using them:

```yaml
kind: GenericControlPlane
group: k8s.gardener.cloud/v1alpha1
metadata:
  name: foo
  namespace: baz
spec:
  kubeAPIServerTemplate: # template of KubeAPIServer from above
    spec:
      config:
        anonymousAuth: false
        allowPrivileged: false
  kubeControllerManagerTemplate: # template of KubeControllerManager from above
    spec:
      config:
        kubeCloudSharedConfiguration:
          allocateNodeCIDRs: true
            # More or less
  kubeSchedulerTemplate: # template of KubeScheduler from above
    spec:
      config:
        schedulerName: default
  version: v1.12.3
status:
  version: v1.12.3
```

When creating this `GenericControlPlane` resource a gardener deployed controller in the Seed cluster creates child `KubeAPIServer`, `KubeScheduler` and `KubeControllerManager` resources, which is handled by individual sub-controllers, creating a K8S control plane.

## Cloud provider implementations:

A cloud-provider specific implementation can look like this:

```yaml
kind: AWSControlPlane
group: aws.k8s.gardener.cloud/v1alpha1
metadata:
  name: foo
  namespace: baz
spec:
  genericControlPlaneTemplate: # template of GenricControlPlane from above
    spec:
      kubeAPIServerTemplate:
        spec:
          config:
            anonymousAuth: false
            allowPrivileged: false
      kubeControllerManagerTemplate:
        spec:
          config:
            kubeCloudSharedConfiguration:
              allocateNodeCIDRs: true
      kubeSchedulerTemplate:
        spec:
          config:
            schedulerName: default
      version: v1.12.3
  readvertiser:
    image: aws.grpc.io/readvertiser:1.3.5
  cloudControllerManager:
    spec: ... # AWS specific configuration
status:
  version: v1.12.3
```

In this case an AWS control plane specific controller shall create `GenericControlPlane` resource and set its `spec.kubeAPIServerTemplate.spec.advertise-address` to `false`, because it'll deploy `aws-readvertiser`. It also deploys an AWS specific cloud-controller.

This opens the possiblity for Providers to reuse the same primitives, but compose them to match their flow..
The example bellow shall create a __virtual__ K8S cluster with only `kube-apiserver` and `kube-controller-manager` and run the federation controllers next to it.

```yaml
kind: FederationControlPlane
group: federation.gardener.cloud/v1alpha1
metadata:
  name: foo
  namespace: baz
spec:
  kubeAPIServerTemplate: # template of KubeAPIServer from above
    spec:
      config:
        # Settings which disable allmost all API, internal controllers and so
        # leaving only the bare-minimum for usesage in federation-v2
      version: v1.12.3
  kubeControllerManagerTemplate: # template of GenricControlPlane from above
    spec:
      config:
        # Settings which disable allmost all almnost all controllers,
        # expect for garbage-collector and serviceaccounts
      version: v1.12.3
  federationConfig:
    image: quay.io/kubernetes-multicluster/federation-v2:latest
```

/cc @rfranzke @vlerenc @vasu1124 @stoyanr
