### ISSUE TITLE
Enable the support for io1 volumes 

### ISSUE THREAD

**Issue by PadmaB** [gardener/gardener-extensions#205]
Expose iops field in the shoot manifest and do the necessary adaptations in Gardener and Shoot API spec to support io1 volumes 

**Note:** Necessary changes have been made in machine-controller-manager, https://github.com/gardener/machine-controller-manager/issues/69

**Comment by rfranzke** [comment]
Done with ddba59f549c2ed50d49bf207242bd56adf126bf2.

End-users will now be able to create `io1` volumes by using the new `core.gardener.cloud/v1alpha1.Shoot` resource. The `.spec.provider.workers[]` list has a field `providerConfig` that they can use to configure the IOPS, e.g.
 
```yaml
spec:
  provider:
    workers:
    - name: cpu-worker
      minimum: 3
      maximum: 5
      volume:
        type: io1
        size: 20Gi
      providerConfig:
        apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
        kind: WorkerConfig
        volume:
          iops: 500 # must be within 100-20000 for io1
    ...
 ```
