### ISSUE TITLE
Implement `Infrastructure` controller for Azure provider

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extensions#23]
Similar to how we have implemented the `Infrastructure` extension resource controller for the [AWS provider](https://github.com/gardener/gardener-extensions/tree/master/controllers/provider-aws/pkg/infrastructure) let's please now do it for Azure.

Based on [the current implementation](https://github.com/gardener/gardener/blob/master/example/90-shoot-azure.yaml#L13-L20) the `InfrastructureConfig` should look like this:

```yaml
apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureConfig
resourceGroup:
  name: mygroup
networks:
  vnet: # specify either 'name' or 'cidr'
  # name: my-vnet
    cidr: 10.250.0.0/16
  workers: 10.250.0.0/19
```

Based on the [current implementation](https://github.com/gardener/gardener/blob/master/charts/seed-terraformer/charts/azure-infra/templates/_main.tf#L67-L93) the `InfrastructureStatus` should look like this:

```yaml
---
apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureStatus
resourceGroup:
  name: mygroup
networks:
  vnet:
    name: my-vnet
  subnets:
  - purpose: nodes
    name: my-subnet
availabilitySets:
- purpose: nodes
  id: av-set-id
  name: av-set-name
routeTables:
- purpose: nodes
  name: route-table-name
securityGroups:
- purpose: nodes
  name: sec-group-name
```

The current infrastructure creation/deletion implementation can be found [here](https://github.com/gardener/gardener/blob/master/pkg/operation/cloudbotanist/azurebotanist/infrastructure.go). Please try to change as little as possible (with every change the risk that we break something increases!) and just move the code over into the extensions infrastructure actuator.
