### ISSUE TITLE
Implement `Infrastructure` controller for Local provider

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extensions#27]
Similar to how we have implemented the `Infrastructure` extension resource controller for the [AWS provider](https://github.com/gardener/gardener-extensions/tree/master/controllers/provider-aws/pkg/infrastructure) let's please now do it for GCP.

Based on [the current implementation](https://github.com/gardener/gardener/blob/master/example/90-shoot-local.yaml#L13-L16) the `InfrastructureConfig` should look like this:

```yaml
apiVersion: local.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureConfig
networks:
  workers: 10.250.0.0/19
endpoint: localhost:3777 # endpoint service pointing to gardener-local-provider
```

Based on the [current implementation](https://github.com/gardener/gardener/blob/master/pkg/operation/cloudbotanist/localbotanist/infrastructure.go#L17-L20) the `InfrastructureStatus` should look like this:

```yaml
---
apiVersion: local.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureStatus
```

The current infrastructure creation/deletion implementation can be found [here](https://github.com/gardener/gardener/blob/master/pkg/operation/cloudbotanist/localbotanist/infrastructure.go).
