### ISSUE TITLE
Make OS controllers capable to support different linux distro families 

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener-extensions#318]
Currently there is OS controllers for the following distros:
* CoreOS Linux
* Ubuntu
* Suse

These OSes are part of Distro families that shares a lot, e.g. Ubuntu and Debian, openSuse and Suse,  CoreOS and FlatCar.

For example, the current coreos controller successfully bootstraps FlatCar Linux nodes, but it cannot be easily configured, because the coreos controller is acting only on `OperatingSystemConfigs` of type `coreos` and this is hard-coded in the extension controller https://github.com/gardener/gardener-extensions/blob/644b5245ea0ef543385db2313a900dc40b71a06a/controllers/os-coreos/pkg/coreos/add.go#L25

A possible solution would be to make the controller configurable.  At the moment `ControllerRegistration` specifies on what kind of resource the controller should act on
https://github.com/gardener/gardener-extensions/blob/644b5245ea0ef543385db2313a900dc40b71a06a/controllers/os-coreos/example/controller-registration.yaml#L8-L9
This configuration should be propagated to the controller.
So, with the following controller registration
```yaml
---
apiVersion: core.gardener.cloud/v1alpha1
kind: ControllerRegistration
metadata:
  name: os-coreos
spec:
  resources:
  - kind: OperatingSystemConfig
    type: coreos
  - kind: OperatingSystemConfig
    type: flatcar
...
```
the os-coreos controller should be able to reconcile `coreos` and `flatcar` at the same time.
