### ISSUE TITLE
Inconsistent naming worker vs workers

### ISSUE THREAD

**Issue by grolu** [gardener/gardener-extensions#412]
The infrastructure configuration for all cloud providers require to specify one or more `worker` networks. The aws / azure infrastructure config call this value `workers`. For consistency reasons and to avoid that future infrastructure extensions use one or the other term, we should align the config.
Example:
aws
```
provider:
    type: aws
    controlPlaneConfig:
      kind: ControlPlaneConfig
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
    infrastructureConfig:
      kind: InfrastructureConfig
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      networks:
        vpc:
          cidr: 10.250.0.0/16
        zones:
          - name: eu-west-1c
            internal: 10.250.112.0/22
            public: 10.250.96.0/22
            workers: 10.250.0.0/19
```
azure
```
provider:
    type: azure
    controlPlaneConfig:
      kind: ControlPlaneConfig
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
    infrastructureConfig:
      kind: InfrastructureConfig
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
      networks:
        vnet:
          cidr: 10.250.0.0/16
        workers: 10.250.0.0/19
```

**vs**

gcp
```
provider:
    type: gcp
    controlPlaneConfig:
      kind: ControlPlaneConfig
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      zone: europe-west1-d
    infrastructureConfig:
      kind: InfrastructureConfig
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      networks:
        worker: 10.250.0.0/19
```

openstack
```
  provider:
    type: openstack
    controlPlaneConfig:
      kind: ControlPlaneConfig
      apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
      loadBalancerProvider: haproxy
      zone: rot_2_1
    infrastructureConfig:
      kind: InfrastructureConfig
      apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
      floatingPoolName: eu-de-200_k8s_vlan462
      networks:
        worker: 10.250.0.0/19
```

alicloud
```
  provider:
    type: alicloud
    controlPlaneConfig:
      kind: ControlPlaneConfig
      apiVersion: alicloud.provider.extensions.gardener.cloud/v1alpha1
      zone: eu-central-1b
    infrastructureConfig:
      kind: InfrastructureConfig
      apiVersion: alicloud.provider.extensions.gardener.cloud/v1alpha1
      networks:
        vpc:
          cidr: 10.250.0.0/16
        zones:
          - name: eu-central-1b
            worker: 10.250.0.0/19
```
