### ISSUE TITLE
Implement `ControlPlane` controller for Azure provider

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extensions#54]
Similar to how we have implemented the `ControlPlane` extension resource controller for the [AWS provider](https://github.com/gardener/gardener-extensions/tree/master/controllers/provider-aws/pkg/controller/controlplane) let's please now do it for Azure.

Based on [the current implementation](https://github.com/gardener/gardener/blob/master/example/90-shoot-azure.yaml) the `ControlPlaneConfig` should look like this:

```yaml
apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
kind: ControlPlaneConfig
cloudControllerManager:
  featureGates:
    CustomResourceValidation: true
```

No `ControlPlaneStatus` needs to be implemented right now (not needed yet).
