### ISSUE TITLE
Implement `Worker` controller for Azure provider

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extensions#72]
Similar to how we have implemented the `Worker` extension resource controller for the [AWS provider](https://github.com/gardener/gardener-extensions/pull/71) let's please now do it for Azure.

There is no special provider config required to be implemented, however, we should have [component configuration](https://github.com/gardener/gardener-extensions/pull/71/files#diff-ec48bd1cd4bb7c2b51603f67ee4bbee3) for the controller that should look as follows:

```yaml
---
apiVersion: azure.provider.extensions.config.gardener.cloud/v1alpha1
kind: ControllerConfiguration
machineImages:
- name: coreos
  version: 1967.5.0
  publisher: CoreOS
  offer: CoreOS
  sku: Stable
```
