### ISSUE TITLE
Implement `Worker` controller for Packet provider

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extensions#82]
Similar to how we have implemented the `Worker` extension resource controller for the [AWS provider](https://github.com/gardener/gardener-extensions/pull/71) let's please now do it for Packet.

*Disclaimer: Based on https://github.com/gardener/gardener/pull/916.*

There is no special provider config required to be implemented, however, we should have [component configuration](https://github.com/gardener/gardener-extensions/pull/71/files#diff-ec48bd1cd4bb7c2b51603f67ee4bbee3) for the controller that should look as follows:

```yaml
---
apiVersion: packet.provider.extensions.config.gardener.cloud/v1alpha1
kind: ControllerConfiguration
machineImages:
- name: coreos
  version: 2023.5.0
  id: d61c3912-8422-4daf-835e-854efa0062e4
```
